-- CreateEnum
CREATE TYPE "MuscleGroup" AS ENUM ('CHEST', 'BACK', 'SHOULDERS', 'ARMS', 'LEGS', 'GLUTES', 'CORE');

-- CreateEnum
CREATE TYPE "Muscle" AS ENUM ('CHEST_GENERAL', 'UPPER_CHEST', 'MIDDLE_CHEST', 'LOWER_CHEST', 'BACK_GENERAL', 'LATS', 'TRAPS', 'LOWER_BACK', 'RHOMBOIDS', 'SHOULDERS_GENERAL', 'FRONT_DELTOID', 'SIDE_DELTOID', 'REAR_DELTOID', 'ARMS_GENERAL', 'BICEPS_LONG_HEAD', 'BICEPS_SHORT_HEAD', 'TRICEPS_LONG_HEAD', 'TRICEPS_LATERAL_HEAD', 'TRICEPS_MEDIAL_HEAD', 'FOREARMS_GENERAL', 'BRACHIORADIALIS', 'PRONATOR_TERES', 'FLEXORS', 'EXTENSORS', 'LEGS_GENERAL', 'QUADRICEPS', 'HAMSTRINGS', 'CALVES', 'GLUTES_GENERAL', 'GLUTEUS_MAXIMUS', 'GLUTEUS_MEDIUS', 'GLUTEUS_MINIMUS', 'CORE_GENERAL', 'ABS', 'OBLIQUES');

-- CreateTable
CREATE TABLE "Exercise" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "muscle_group" "MuscleGroup" NOT NULL,
    "muscle" "Muscle" NOT NULL,

    CONSTRAINT "Exercise_pkey" PRIMARY KEY ("id")
);
